ARG PGVERSION=18
FROM postgres:${PGVERSION}

ARG PGVERSION=18
USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends postgresql-${PGVERSION}-wal2json \
    && rm -rf /var/lib/apt/lists/*
USER postgres
